server:
  port: 8080
spring:
  application:
    name: websocket-group-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-211-221-185.compute-1.amazonaws.com:5432/da068g65nkn84h
    username: jccdqbqlgpzycp
    password: 591d712f7b2010b050616f624a529781352632f52c7163969059f790ba4d4fd6
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never