server:
  port: 8080
spring:
  application:
    name: task5
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-198-186-145.compute-1.amazonaws.com:5432/d9lcrn9t188d31
    username: uayvndjkrttcnr
    password: 82b56d97c383b372cad7acd30e0ba60351326227b0affe191276022294cfa52b
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
