server:
  port: 8080

spring:
  application:
    name: websocket-group-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/itransition_task5
    username: postgres
    password: matem2003
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never